# Generated by Django 5.1.1 on 2024-09-27 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('instructor', 'Instructor')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('New Capital', 'NEW Capital'), ('Mansoura', 'Mansoura'), ('Cairo University', 'Cairo University'), ('Smart Village', 'Smart Village'), ('Aswan', 'Aswan'), ('Asuit', 'Asuit'), ('Qena', 'Qena'), ('Menia', 'Menia'), ('Menofia', 'Menofia'), ('Beni Suef', 'Beni Suef'), ('Sohag', 'Sohag'), ('Ismalilia', 'Ismalilia'), ('Alexendria', 'Alexendria')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
