# Generated by Django 5.1.1 on 2024-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('1', 'New Capital'), ('2', 'Mansoura'), ('3', 'Cairo University'), ('4', 'Assuit')], max_length=30),
        ),
    ]
